name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: bump type
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
      - run: |
          yarn test
      - run: |
          tsc
  TagAndRelease:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.TOKEN }}
          default_bump: ${{ github.event.inputs.bump }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: './export/AmazonLexTemplates.zip, ./export/GoogleDialogFlowCXTemplates.blob, ./export/CustomIntegrationTemplates.zip, ./export/BotFramework.zip, ./export/Composer.zip, ./export/IbmWatson.json, ./export/DialogflowES.zip'
